### ISSUE TITLE
当连接池中没有连接的时候，会一直去创建新的连接

### ISSUE THREAD

**Issue by philchia** [silenceper/pool#16]
MaxCap 这个只是限制了池中的连接的数量，并发量高的时候，会有大量的新的连接产生

**Comment by silenceper** [comment]
是的，当连接池中已经有MaxCap个连接正在使用，如果还有新连接请求时，这里并没有去拒绝新的连接。

这里可能可以加上一个配置参数，来控制当超过最大连接数拒绝新链接请求，不过就会影响业务系统正常使用了。

**Comment by philchia** [comment]
可以跟踪下已经创建的连接数量，当已经创建的连接数量大于MaxCap的时候，等待连接池返回一个连接或者做超时处理，否则就创建一个新连接

**Comment by silenceper** [comment]
这个可以有，作为一个Feature  👍

**Comment by guoyucheng** [comment]
咋样啊 兄de 这个问题太坑了啊 有解决办法吗？
