### ISSUE TITLE
如果池子满了，客户端会直接返回error吗

### ISSUE THREAD

**Issue by imxyb** [silenceper/pool#28]
我更希望的是，像go的db连接池那样，池子满了应该进入一个队列，等待一段时间，然后再返回错误。

**Comment by silenceper** [comment]
这里返回的是一个 pool. ErrMaxActiveConnReached 的错误

**Comment by imxyb** [comment]
给你提了个pr，实现类似go的db连接池那样的机制，当pool满了进行队列等待，put的时候优先给队列等待的请求发送空闲连接，麻烦review一下

**Comment by imxyb** [comment]
https://github.com/silenceper/pool/pull/29 @silenceper
