### ISSUE TITLE
关于 `PUT` 方法的疑问

### ISSUE THREAD

**Issue by SaneHe** [silenceper/pool#36]
![image](https://user-images.githubusercontent.com/28290710/182008561-b63f49aa-a026-4447-b579-9f6499d5f918.png)

`PUT` 方法中的这个 `req` 是什么意思呢

**Comment by silenceper** [comment]
ref: https://github.com/silenceper/pool/pull/29 

正在等待获取conn的请求

**Comment by SaneHe** [comment]
@silenceper OK
